#!/usr/bin/env bash
set -euo pipefail

# ── reset-branches.sh ───────────────────────────────────────────────────────────
# Resets develop, stage, and autogenerated to match the current master branch.
# Usage: ./reset-branches.sh [--push]

PUSH=false
if [[ "${1:-}" == "--push" ]]; then
    PUSH=true
fi

# Ensure we're in a git repo
if ! git rev-parse --git-dir &>/dev/null; then
    echo "ERROR: Not inside a Git repository." >&2
    exit 1
fi

BRANCHES=("develop" "stage" "autogenerated")
CURRENT_BRANCH=$(git branch --show-current)

# ── Safety checks ──────────────────────────────────────────────────────────────

# Warn about uncommitted changes
if ! git diff-index --quiet HEAD -- 2>/dev/null; then
    echo "WARNING: You have uncommitted changes. Stash or commit them first." >&2
    echo "Uncommitted files:" >&2
    git status --short
    exit 1
fi

# Verify all target branches exist locally
for branch in "${BRANCHES[@]}"; do
    if ! git show-ref --verify --quiet "refs/heads/$branch"; then
        echo "ERROR: Local branch '$branch' does not exist." >&2
        exit 1
    fi
done

# ── Confirmation ───────────────────────────────────────────────────────────────

echo "This will HARD RESET the following branches to match 'master':"
for branch in "${BRANCHES[@]}"; do
    echo "  • $branch"
done
if $PUSH; then
    echo ""
    echo "After reset, branches will be FORCE PUSHED to origin."
fi
echo ""
read -r -p "Type 'yes' to confirm: " CONFIRM

if [[ "$CONFIRM" != "yes" ]]; then
    echo "Aborted."
    exit 0
fi

# ── Reset branches ─────────────────────────────────────────────────────────────

echo ""
echo "Switching to master..."
git checkout master

for branch in "${BRANCHES[@]}"; do
    echo ""
    echo "── Resetting '$branch' ──"
    git checkout "$branch"
    git reset --hard master
done

if $PUSH; then
    echo ""
    for branch in "${BRANCHES[@]}"; do
        echo "── Force pushing '$branch' to origin ──"
        git push --force-with-lease origin "$branch"
    done
fi

# ── Back to original branch ───────────────────────────────────────────────────

echo ""
echo "Returning to '$CURRENT_BRANCH'..."
git checkout "$CURRENT_BRANCH"

echo ""
echo "✓ Done. All branches now match master."
